### ISSUE TITLE
[Feature] Images link to torrents

### ISSUE THREAD

**Issue by sjclayton** [tim784/ropes#17]
Just wondering if it would be possible to have clicking directly on an image go straight to the chosen torrent. =)

Thanks in advance! Keep up the awesome work.

**Comment by tim784** [comment]
Oh, hello! This slipped past me.

I think this is a good idea. Can do.

I've actually written several versions of this project for personal use over many years, and had this functionality in it before. Forgot about bringing this in this time.

**Comment by tim784** [comment]
Added in https://github.com/tim784/ropes/commit/f3a22a7487de85e5aa37226842b073b77a2bc29e

Will be released in 13.0.0, perhaps tonight.

Thanks for requesting this! Let me know if there's anything else you'd like to see.

**Comment by tim784** [comment]
Finally released.
